import { CommanderSuggestion, GeneratedDeck, WishlistItem } from '@/types/builder';
import { MOCK_CARDS } from './cards';

export const MOCK_COMMANDERS: CommanderSuggestion[] = [
  {
    id: 'cmd-1',
    name: "Atraxa, Praetors' Voice",
    imageUrl: 'https://cards.scryfall.io/normal/front/d/0/d0d0.jpg',
    colors: ['W', 'U', 'B', 'G'],
    colorIdentity: ['W', 'U', 'B', 'G'],
    ownershipCoverage: 75,
    missingStaplesCount: 2,
    estimatedCostToComplete: 45.0,
    popularityRank: 1,
    typeLine: 'Legendary Creature — Phyrexian Angel',
  },
  {
    id: 'cmd-2',
    name: 'Krenko, Mob Boss',
    imageUrl: 'https://cards.scryfall.io/normal/front/c/d/cdcd.jpg',
    colors: ['R'],
    colorIdentity: ['R'],
    ownershipCoverage: 92,
    missingStaplesCount: 0,
    estimatedCostToComplete: 12.5,
    popularityRank: 4,
    typeLine: 'Legendary Creature — Goblin Warrior',
  },
  {
    id: 'cmd-3',
    name: 'Edgar Markov',
    imageUrl: 'https://cards.scryfall.io/normal/front/8/d/8d8d.jpg',
    colors: ['R', 'W', 'B'],
    colorIdentity: ['R', 'W', 'B'],
    ownershipCoverage: 68,
    missingStaplesCount: 4,
    estimatedCostToComplete: 89.0,
    popularityRank: 2,
    typeLine: 'Legendary Creature — Vampire Knight',
  },
  {
    id: 'cmd-4',
    name: 'The Ur-Dragon',
    imageUrl: 'https://cards.scryfall.io/normal/front/7/e/7e7e.jpg',
    colors: ['W', 'U', 'B', 'R', 'G'],
    colorIdentity: ['W', 'U', 'B', 'R', 'G'],
    ownershipCoverage: 55,
    missingStaplesCount: 6,
    estimatedCostToComplete: 140.0,
    popularityRank: 3,
    typeLine: 'Legendary Creature — Dragon Avatar',
  },
];

export function createMockGeneratedDeck(commander: CommanderSuggestion): GeneratedDeck {
  const isKrenko = commander.id === 'cmd-2';
  const solRing = MOCK_CARDS.find((c) => c.name.toLowerCase().includes('sol ring')) || MOCK_CARDS[0];

  const cardsCount = 100;
  const ownedCardsCount = Math.round((commander.ownershipCoverage / 100) * cardsCount);
  const wishlistCardsCount = cardsCount - ownedCardsCount;

  return {
    id: `generated-${commander.id}`,
    name: `${commander.name} Synergistic Deck Engine`,
    commander,
    totalCards: 100,
    ownedPercentage: commander.ownershipCoverage,
    ownedCardsCount,
    wishlistCardsCount,
    unfillableSlotsCount: 0,
    wishlistTotalCost: commander.estimatedCostToComplete,
    averageManaValue: isKrenko ? 2.45 : 3.12,
    powerLevel: 7,
    buildScore: isKrenko ? 94 : 91,
    legalityWarnings: [
      {
        severity: 'warning',
        rule: 'Format Rule Validation',
        message: 'Deck fully compliant with Commander format legalities (100 cards, Singleton rule verified).',
      },
    ],
    cards: [
      {
        card: solRing,
        quantity: 1,
        section: 'Ramp',
        ownership: 'owned',
        estimatedPrice: 1.5,
        synergyScore: 98,
        synergyReason: 'Universal ramp staple providing +2 mana acceleration.',
      },
      {
        card: {
          id: 'mock-synergy-1',
          oracleId: 'ora-syn-1',
          name: isKrenko ? 'Goblin Chieftain' : 'Doubling Season',
          manaCost: isKrenko ? '{1}{R}{R}' : '{4}{G}',
          manaValue: isKrenko ? 3 : 5,
          colors: isKrenko ? ['R'] : ['G'],
          colorIdentity: isKrenko ? ['R'] : ['G'],
          typeLine: isKrenko ? 'Creature — Goblin' : 'Enchantment',
          setCode: 'cmm',
          setName: 'Commander Masters',
          rarity: 'rare',
          legalities: { commander: 'legal' },
        },
        quantity: 1,
        section: 'Theme/Synergy',
        ownership: 'wishlist',
        estimatedPrice: isKrenko ? 3.5 : 38.5,
        synergyScore: 99,
        synergyReason: isKrenko
          ? 'Grants haste and anthem buff to all tokens generated by Krenko.'
          : 'Doubles all counters placed by proliferate triggers.',
      },
    ],
  };
}

export function extractWishlistFromDeck(deck: GeneratedDeck): WishlistItem[] {
  return deck.cards
    .filter((c) => c.ownership === 'wishlist')
    .map((c) => ({
      card: c.card,
      priority: c.synergyScore >= 95 ? 'High Synergy' : 'Key Staple',
      estimatedPrice: c.estimatedPrice,
      acquired: false,
      quantity: c.quantity,
    }));
}
