import { Card } from '@/types/card';

export const MOCK_CARDS: Card[] = [
  {
    id: 'spidey-hero',
    oracleId: 'spidey-o-1',
    name: 'Spider-Man, Neighborhood Hero',
    manaCost: '{1}{U}{R}',
    manaValue: 3,
    colors: ['U', 'R'],
    colorIdentity: ['U', 'R'],
    typeLine: 'Legendary Creature — Hero Human',
    oracleText: 'Reach, Haste\nWhenever Spider-Man deals combat damage to a player, draw a card.',
    power: '3',
    toughness: '3',
    setCode: 'MARVEL',
    setName: 'Marvel Super Heroes MTG',
    rarity: 'mythic',
    legalities: { commander: 'legal' },
  },
  {
    id: 'spidey-peter-parker',
    oracleId: 'spidey-o-2',
    name: 'Spider-Man, Peter Parker',
    manaCost: '{2}{U}{R}',
    manaValue: 4,
    colors: ['U', 'R'],
    colorIdentity: ['U', 'R'],
    typeLine: 'Legendary Creature — Hero Human Spider',
    oracleText: 'Reach, First Strike\nWhenever you cast a hero spell, Spider-Man gets +1/+1 until end of turn.',
    power: '3',
    toughness: '4',
    setCode: 'MARVEL',
    setName: 'Marvel Super Heroes MTG',
    rarity: 'mythic',
    legalities: { commander: 'legal' },
  },
  {
    id: 'ironman-hero',
    oracleId: 'ironman-o-1',
    name: 'Iron Man, Tech Innovator',
    manaCost: '{2}{U}{R}{W}',
    manaValue: 5,
    colors: ['U', 'R', 'W'],
    colorIdentity: ['U', 'R', 'W'],
    typeLine: 'Legendary Artifact Creature — Hero Engineer',
    oracleText: 'Flying, Ward {2}\nArtifact spells you cast cost {1} less to cast.',
    power: '4',
    toughness: '5',
    setCode: 'MARVEL',
    setName: 'Marvel Super Heroes MTG',
    rarity: 'mythic',
    legalities: { commander: 'legal' },
  },
  {
    id: 'wolverine-hero',
    oracleId: 'wolverine-o-1',
    name: 'Wolverine, Mutant Berserker',
    manaCost: '{1}{R}{G}',
    manaValue: 3,
    colors: ['R', 'G'],
    colorIdentity: ['R', 'G'],
    typeLine: 'Legendary Creature — Hero Mutant',
    oracleText: 'Trample, Indestructible\nWhenever Wolverine is dealt damage, put two +1/+1 counters on it.',
    power: '3',
    toughness: '2',
    setCode: 'MARVEL',
    setName: 'Marvel Super Heroes MTG',
    rarity: 'rare',
    legalities: { commander: 'legal' },
  },
  {
    id: 'cap-america',
    oracleId: 'cap-o-1',
    name: 'Captain America, First Avenger',
    manaCost: '{2}{R}{W}',
    manaValue: 4,
    colors: ['R', 'W'],
    colorIdentity: ['R', 'W'],
    typeLine: 'Legendary Creature — Hero Soldier',
    oracleText: 'Vigilance\nOther Heroes you control get +1/+1 and have vigilance.',
    power: '4',
    toughness: '4',
    setCode: 'MARVEL',
    setName: 'Marvel Super Heroes MTG',
    rarity: 'mythic',
    legalities: { commander: 'legal' },
  },
  {
    id: 'thor-god',
    oracleId: 'thor-o-1',
    name: 'Thor, God of Thunder',
    manaCost: '{3}{R}{R}{W}',
    manaValue: 6,
    colors: ['R', 'W'],
    colorIdentity: ['R', 'W'],
    typeLine: 'Legendary Creature — God Hero',
    oracleText: 'Flying, Trample\nWhen Thor enters the battlefield, it deals 3 damage to each creature your opponents control.',
    power: '6',
    toughness: '6',
    setCode: 'MARVEL',
    setName: 'Marvel Super Heroes MTG',
    rarity: 'mythic',
    legalities: { commander: 'legal' },
  },
  {
    id: 'hulk-smash',
    oracleId: 'hulk-o-1',
    name: 'The Incredible Hulk',
    manaCost: '{4}{G}{G}',
    manaValue: 6,
    colors: ['G'],
    colorIdentity: ['G'],
    typeLine: 'Legendary Creature — Hero Mutant',
    oracleText: 'Trample\nThe Incredible Hulk gets +1/+1 for each damage marked on it.',
    power: '7',
    toughness: '7',
    setCode: 'MARVEL',
    setName: 'Marvel Super Heroes MTG',
    rarity: 'mythic',
    legalities: { commander: 'legal' },
  },
  {
    id: 'black-widow',
    oracleId: 'bw-o-1',
    name: 'Black Widow, Master Spy',
    manaCost: '{1}{U}{B}',
    manaValue: 3,
    colors: ['U', 'B'],
    colorIdentity: ['U', 'B'],
    typeLine: 'Legendary Creature — Hero Rogue',
    oracleText: 'Deathtouch, Skulk\nWhen Black Widow deals combat damage to a player, look at their hand and you may choose a nonland card from it. Exile that card.',
    power: '2',
    toughness: '2',
    setCode: 'MARVEL',
    setName: 'Marvel Super Heroes MTG',
    rarity: 'rare',
    legalities: { commander: 'legal' },
  },
  {
    id: 'dr-strange',
    oracleId: 'strange-o-1',
    name: 'Doctor Strange, Sorcerer Supreme',
    manaCost: '{3}{U}{R}',
    manaValue: 5,
    colors: ['U', 'R'],
    colorIdentity: ['U', 'R'],
    typeLine: 'Legendary Creature — Hero Wizard',
    oracleText: 'Flying\n{T}: Return target instant or sorcery card from your graveyard to your hand. Exile it if it would leave your hand.',
    power: '3',
    toughness: '4',
    setCode: 'MARVEL',
    setName: 'Marvel Super Heroes MTG',
    rarity: 'mythic',
    legalities: { commander: 'legal' },
  }
];
